import {seedChanged, gsChanged, generatedImageHovered, generatedImageMouseOut, textVectorGeneratorClicked, latentDenoiserClicked} from "./function.js"

let architectureLineWidth = 2;
// let architectureLineColor = "#e8e8e8ff"
let architectureLineColor = "#b0b0b0"

window.textVectorGeneratorL2Expanded = false;
window.textVectorGeneratorL3Expanded = false;
window.latentDenoiserL2Expanded = false;
window.latentDenoiserL3Expanded = false;

d3.select("#architecture-container")
    .append("div")
    .attr("id", "stable-diffusion-description-text")
    .text("Guided by the vectors for text prompt, randomly initialized low-dimensional latent vector is denoised over timesteps. Decoder scales up the latent vector to generate a high-resolution image.")

d3.select("#architecture-container")
    .append("div")
        .attr("id", "hyperparameter-control-show-hide-container")
d3.select("#hyperparameter-control-show-hide-container")
        .append("img")
            .attr("id", "hyperparameter-control-show-hide-img")
            .attr("src", "./icons/pencil.svg")
            .attr("width", "10px")
d3.select("#hyperparameter-control-show-hide-container")
    .on("mouseover", (e) => {
        d3.select("#hyperparameter-control-show-hide-container").style("color", "#808080");
        d3.select("#hyperparameter-control-show-hide-img").style("filter", "invert(53%) sepia(20%) saturate(0%) hue-rotate(262deg) brightness(90%) contrast(85%)"); 
        d3.select("#hyperparameter-control-show-hide-container").style("border-color", "#808080")
    })
    .on("mouseout", (e) => {
        d3.select("#hyperparameter-control-show-hide-container").style("color", "#bdbdbd");
        d3.select("#hyperparameter-control-show-hide-img").style("filter", "invert(68%) sepia(23%) saturate(0%) hue-rotate(274deg) brightness(100%) contrast(113%)"); 
        d3.select("#hyperparameter-control-show-hide-container").style("border-color", "#bdbdbd")
    })
    .on("click", (e) => {
        let guidanceDisplayed = (d3.select("#unet-guidance-scale-control-container").style("opacity") == "1")
        let seedDisplayed = (d3.select("#unet-in-noise-seed-control-container").style("opacity") == "1")
        if (guidanceDisplayed && seedDisplayed) {
            d3.select("#unet-guidance-scale-control-container")
                .transition()
                .duration(300)
                .style("opacity", 0)
            d3.select("#unet-in-noise-seed-control-container")
                .transition()
                .duration(300)
                .style("opacity", 0)
            d3.select("#hyperparameter-control-show-hide-text")
                .text(" Show Hyperparameters")
                .style("padding-left", "1px")
        }
        else {
            d3.select("#unet-guidance-scale-control-container")
                .transition()
                .duration(300)
                .style("opacity", 1)
            d3.select("#unet-in-noise-seed-control-container")
                .transition()
                .duration(300)
                .style("opacity", 1)
            d3.select("#hyperparameter-control-show-hide-text")
                .text(" Hide Hyperparameters")
                .style("padding-left", "5px")
        }
    })
d3.select("#hyperparameter-control-show-hide-container")
    .append("div")
    .attr("id", "hyperparameter-control-show-hide-text")
    .text("Show Hyperparameters")

d3.select("#architecture-container")
    .append("svg")
        .attr("height", 0)
        .attr("width", 0)
        .append("defs")
            .append("marker")
                .attr("id", "architecture-arrow-head")
                .attr("markerWidth", "10")
                .attr("markerHeight", "4")
                .attr("refX", "0")
                .attr("refY", "2")
                .attr("orient", "auto")
                .append("polygon")
                    .attr("points", "0 0, 4 2, 0 4")
                    .attr("fill", architectureLineColor)

d3.select("#architecture-container")
    .append("div")
        .attr("id", "your-prompt-container")
        .attr("class", "architecture-component-container denoise-latent-expand-move-to-left")
d3.select("#your-prompt-container")
    .append("div")
        .attr("id", "your-prompt-text")
        .append("div")
            .attr("id", "your-prompt-text-prompt")

d3.select("#your-prompt-container")
    .append("svg")
        .attr("id", "your-prompt-svg")
        .attr("class", "architecture-svg")
        .append("defs") 
            .append("linearGradient")
                .attr("id", "your-prompt-gradient")
                .attr("gradientUnits", "userSpaceOnUse")
                .attr("x1", "0")
                .attr("y1", "0")
                .attr("x2", "100%")
                .attr("y2", "0")
d3.select("#your-prompt-gradient")
    .append("stop")
        .attr("offset", "0%")
        .attr("stop-color", "#e8e8e800")
d3.select("#your-prompt-gradient")
    .append("stop")
        .attr("offset", "100%")
        .attr("stop-color", architectureLineColor)
d3.select("#your-prompt-svg")
    .append("g")
        .append("line")
            .attr("id", "your-prompt-arrow")
            .attr("x1", "0")
            .attr("y1", "10")
            .attr("x2", "82")
            .attr("y2", "10")
            .attr("stroke", "url(#your-prompt-gradient)")
            .attr("stroke-width", architectureLineWidth)
            .attr("marker-end", "url(#architecture-arrow-head)")

d3.select("#architecture-container")
    .append("div")
        .attr("id", "generate-text-vector-container")
        .attr("class", "architecture-component-container denoise-latent-expand-move-to-left")
        .on("mouseover", () => {
            if (!window.textVectorGeneratorL2Expanded) d3.select("#generate-text-vector-rectangle").style("fill", "#e0e0e0")
        })
        .on("mouseout", () => {
            d3.select("#generate-text-vector-rectangle").style("fill", "none")
        })
        .on("click", textVectorGeneratorClicked)
        .append("svg")
            .attr("id", "generate-text-vector-svg")
            .attr("class", "architecture-svg")
            .append("rect")
                .attr("id", "generate-text-vector-rectangle")
                .attr("class", "architecture-rectangle")
                .attr("width", "100")
                .attr("height", "50")
                .attr("rx", "5")
                .attr("ry", "5")
d3.select("#generate-text-vector-container")
    .append("div")
    .attr("id", "generate-text-vector-text")
    .attr("class", "architecture-text")
    .text("Text Vector Generator")


d3.select("#architecture-container")
    .append("div")
        .attr("id", "generate-text-vector-denoise-latent-container")
        .attr("class", "architecture-component-container denoise-latent-expand-move-to-left")
            .append("svg")
                .attr("id", "generate-text-vector-denoise-latent-svg")
                .attr("class", "architecture-svg")
                .append("g")
                    .append("line")
                        .attr("id", "generate-text-vector-denoise-latent-arrow")
                        .attr("x1", "0")
                        .attr("y1", "10")
                        .attr("x2", "152")
                        .attr("y2", "10")
                        .attr("stroke", architectureLineColor)
                        .attr("stroke-width", architectureLineWidth)
                        .attr("marker-end", "url(#architecture-arrow-head)")
d3.select("#generate-text-vector-denoise-latent-container")
    .append("div")
    .text("Text Vectors")
    .attr("id", "generate-text-vector-denoise-latent-guide-text")

d3.select("#generate-text-vector-denoise-latent-svg").append("defs").append("linearGradient").attr("id", "generate-text-vector-denoise-latent-gradient").attr("gradientUnits", "userSpaceOnUse").attr("x1", "42").attr("y1", "0").attr("x2", "100").attr("y2", "0")
d3.select("#generate-text-vector-denoise-latent-gradient")
    .append("stop")
        .attr("offset", "0%")
        .attr("stop-color", "#51B3D240")
d3.select("#generate-text-vector-denoise-latent-gradient")
    .append("stop")
        .attr("offset", "100%")
        .attr("stop-color", "#51B3D200")

let clipUnetTokenVectorG = d3.select("#generate-text-vector-denoise-latent-svg").append("g").attr("id", "generate-text-vector-denoise-latent-svg-token-vector-g")
let clipUnetTokenVectorsContainer = d3.select("#generate-text-vector-denoise-latent-container").append("div").attr("id", "generate-text-vector-denoise-latent-token-vectors-container")
clipUnetTokenVectorsContainer.append("div").attr("id", "generate-text-vector-denoise-latent-tokens-container")
clipUnetTokenVectorsContainer.append("div").attr("id", "generate-text-vector-denoise-latent-vectors-container")

clipUnetTokenVectorG.append("circle").attr("r", "1.5").attr("cx", "69").attr("cy", "100").attr("class", "dots")
clipUnetTokenVectorG.append("circle").attr("r", "1.5").attr("cx", "69").attr("cy", "106").attr("class", "dots")
clipUnetTokenVectorG.append("circle").attr("r", "1.5").attr("cx", "69").attr("cy", "112").attr("class", "dots")

d3.select("#architecture-container")
    .append("div")
        .attr("id", "denoise-latent-cycle-container")
        .attr("class", "architecture-component-container text-vector-generator-expand-move-to-right")
        .append("svg")
            .attr("id", "denoise-latent-cycle-svg")
            .attr("class", "architecture-svg")
            .append("g")
                .append("path")
                    .attr("id", "denoise-latent-cycle")
                    .attr("class", "architecture-dashed")
                    .attr("stroke-width", architectureLineWidth)
                    .attr("stroke", architectureLineColor)
                    .attr("marker-end", "url(#architecture-arrow-head)")
                    .attr("fill", "none")
                    .attr("d", "M 257,128.5 l0 -55.5 a5,5 0 0 0 -5,-5 l-245,0 a5,5 0 0 0 -5,5 l0,41 a5,5 0 0 0 5,5 l47,0")
                    .style("animation-name", "unet-cycle-animation")
                    .style("animation-play-state", "paused")
d3.select("#denoise-latent-cycle-container")
    .append("div")
    .attr("id", "denoise-latent-cycle-latent-text")
    .text("Latent")

d3.select("#architecture-container")
    .append("div")
        .attr("id", "denoise-latent-container")
        .attr("class", "architecture-component-container text-vector-generator-expand-move-to-right")
        .on("mouseover", () => {
            if (!window.latentDenoiserL2Expanded) d3.select("#denoise-latent-rectangle").style("fill", "#e0e0e0")
        })
        .on("mouseout", () => {
            d3.select("#denoise-latent-rectangle").style("fill", "none")
        })
        .on("click", function (e) {
            if (!latentDenoiserL2Expanded) latentDenoiserClicked(e);
        })
        .append("svg")
            .attr("id", "denoise-latent-svg")
            .attr("class", "architecture-svg")
            .append("rect")
                .attr("id", "denoise-latent-rectangle")
                .attr("class", "architecture-rectangle")
                .attr("width", "140")
                .attr("height", "105")
                .attr("rx", "5")
                .attr("ry", "5")

d3.select("#denoise-latent-container")
    .append("div")
        .attr("id", "denoise-latent-text")
        .attr("class", "architecture-text")
        .text("Latent Denoiser")
d3.select("#denoise-latent-container")
    .append("div")
        .attr("id", "predict-noise")
        .text("Predict Noise")
d3.select("#denoise-latent-container")
    .append("div")
        .attr("id", "remove-noise")
        .text("Remove Noise")



d3.select("#architecture-container")
    .append("div")
        .attr("id", "unet-in-noise-container")
        .attr("class", "architecture-component-container text-vector-generator-expand-move-to-right")
        .append("svg")
            .attr("id", "unet-in-noise-svg")
            .attr("class", "architecture-svg")

d3.select("#unet-in-noise-container")
    .append("div")
        .attr("id", "unet-in-noise-seed-control-container")
        .attr("class", "hyperparameter")
d3.select("#unet-in-noise-seed-control-container")
    .append("div")
        .attr("id", "unet-in-noise-seed-control-text-container")
d3.select("#unet-in-noise-seed-control-text-container")
    .append("div")
        .attr("id", "unet-in-noise-seed-control-text-1")
        .text("Seed")
d3.select("#unet-in-noise-seed-control-text-container")
    .append("div")
        .attr("id", "unet-in-noise-seed-control-text-2")
        .text("for latent initialization at step 0:")
d3.select("#unet-in-noise-seed-control-container")
    .append("div")
        .attr("id", "unet-in-noise-seed-control-dropdown-container")
        .attr("class", "custom-select hyperparameter-dropdown-container")
            .append("select")
                .on("change", seedChanged)
                .selectAll("option")
                    .data(["0","1","2","3"])
                    .enter()
                    .append("option")
                        .attr("value", d => d)
                        .text(d => d)

d3.select("#architecture-container").append("div")
    .attr("id", "denoise-latent-decoder-container") // animate arrow
    .attr("class", "architecture-component-container text-vector-generator-expand-move-to-right denoise-latent-expand-move-to-right")
    .append("svg")
        .attr("id", "denoise-latent-decoder-svg")
        .attr("class", "architecture-svg")
        .append("g")
            .append("line")
                .attr("id", "denoise-latent-decoder-arrow")
                .attr("class", "architecture-dashed")
                .attr("x1", "0")
                .attr("y1", "10")
                .attr("x2", "83")
                .attr("y2", "10")
                .attr("stroke", architectureLineColor)
                .attr("stroke-width", architectureLineWidth)
                .attr("marker-end", "url(#architecture-arrow-head)")
                .style("animation-name", "unet-decoder-arrow-animation")
                .style("animation-play-state", "paused")

d3.select("#architecture-container")
    .append("div")
        .attr("id", "denoise-latent-out-noise-container")
        .attr("class", "architecture-component-container text-vector-generator-expand-move-to-right  denoise-latent-expand-move-to-right")
        .append("img")
            .attr("id", "denoise-latent-out-noise-img")

                
d3.select("#denoise-latent-out-noise-container")
    .append("div")
        .attr("id", "denoise-latent-out-noise-expl-container")
d3.select("#denoise-latent-out-noise-expl-container").append("div").attr("id", "denoise-latent-out-noise-expl-text-1").text("Improved")
d3.select("#denoise-latent-out-noise-expl-container").append("div").attr("id", "denoise-latent-out-noise-expl-text-2").text("Latent")


d3.select("#architecture-container")
.append("div")
    .attr("id", "decoder-container") // almost same as tokenizer
    .attr("class", "architecture-component-container text-vector-generator-expand-move-to-right  denoise-latent-expand-move-to-right")
    .append("svg")
        .attr("id", "decoder-svg")
        .attr("class", "architecture-svg")
        .append("rect")
            .attr("id", "decoder-rectangle")
            .attr("class", "architecture-rectangle")
            .attr("width", "75")
            .attr("height", "33")
            .attr("rx", "5")
            .attr("ry", "5")
d3.select("#decoder-svg")
    .append("text")
        .attr("id", "decoder-text")
        .attr("class", "architecture-text")
        .attr("x", "8")
        .attr("y", "22")
        .text("Upscaler")

d3.select("#architecture-container").append("div")
    .attr("id", "decoder-generated-image-container")
    .attr("class", "architecture-component-container text-vector-generator-expand-move-to-right  denoise-latent-expand-move-to-right")
    .append("svg")
        .attr("id", "decoder-generated-image-svg")
        .attr("class", "architecture-svg")
        .append("g")
            .append("line")
                .attr("id", "decoder-generated-image-arrow")
                .attr("class", "architecture-dashed")
                .attr("x1", "0")
                .attr("y1", "10")
                .attr("x2", "21")
                .attr("y2", "10")
                .attr("stroke", architectureLineColor)
                .attr("stroke-width", architectureLineWidth)
                .attr("marker-end", "url(#architecture-arrow-head)")
                .style("animation-name", "unet-decoder-arrow-animation")
                .style("animation-play-state", "paused")

let generatedImageContainerDiv = d3.select("#architecture-container")
    .append("div")
        .attr("id", "generated-image-container")
        .attr("class", "architecture-component-container text-vector-generator-expand-move-to-right  denoise-latent-expand-move-to-right")

// TODO: Fix unet guidance scale control container
d3.select("#architecture-container")
    .append("div")
        .attr("id", "unet-guidance-scale-control-container")
        .attr("class", "hyperparameter")
d3.select("#unet-guidance-scale-control-container")
    .append("div")
        .attr("id", "unet-guidance-scale-control-text-container")
d3.select("#unet-guidance-scale-control-text-container")
    .append("div")
        .attr("id", "unet-guidance-scale-control-text")
        .text("Guidance Scale")
d3.select("#unet-guidance-scale-control-container")
    .append("div")
        .attr("id", "unet-guidance-scale-control-dropdown-container")
        .attr("class", "custom-select hyperparameter-dropdown-container")
            .append("select")
                .attr("id", "unet-guidance-scale-control-dropdown-select")
                .on("change", gsChanged)
                .selectAll("option")
                    .data(["1.0","7.0","20.0"])
                    .enter()
                    .append("option")
                        .attr("value", d => d)
                        .text(d => d)
                        .property("selected", d => (d=="7.0"))

// d3.json("./assets/json/data.json").then(
Promise.all([
    d3.json("./assets/json/data.json"),
    d3.json("./assets/json/text.json")
]).then(
    function(files){
        let data = files[0]
        // texts = files[1]
        let timestep = document.getElementById("controller").timestep;
        window.selectedPromptGroupName = Object.keys(data)[window.selectedPromptGroupIdx]
        let selectedData = data[window.selectedPromptGroupName];
        console.log(selectedData);

        d3.select("#denoise-latent-out-noise-img")
            .attr("src", `./assets/latents/${selectedPromptGroupName}/${selectedData["prompts"][0]}_${timestep}_${seed}_${gs}.jpg`)
        d3.select("#denoise-latent-out-noise-container")
                .append("div")
                    .attr("id", "denoise-latent-out-latent-timestep")
                    .text("31")
        generatedImageContainerDiv.append("img")
            .attr("id", "generated-image")
            .attr("src", `./assets/images/${selectedPromptGroupName}/scheduled/${selectedData["prompts"][0]}_${timestep}_${seed}_${gs}.jpg`)
            .on("mouseover", generatedImageHovered)
            .on("mouseout", generatedImageMouseOut)
        generatedImageContainerDiv.append("img")
            .attr("id", "generated-image-2")
            .attr("src", `./assets/images/${selectedPromptGroupName}/scheduled/${selectedData["prompts"][1]}_${timestep}_${seed}_${gs}.jpg`)
            .on("mouseover", generatedImageHovered)
            .on("mouseout", generatedImageMouseOut)
        let promptWordList = window.selectedPrompt1.split(" ")
        d3.select("#your-prompt-text-prompt")
            .text(`${promptWordList[0]} ${promptWordList[1]} ${promptWordList[2]}...`)

        // TEXT TOKENS
        data = files[1];
        let tokens = data[window.selectedPromptGroupName]["token"][selectedPrompt1]
        let vectors = data[window.selectedPromptGroupName]["vector"][selectedPrompt1]
        tokens[0] = "<start>"
        window.tokens = tokens
        let tokenNum = 3;
        let vectorDim = 3;
        for (let i = 0 ; i < tokenNum; i++){
            d3.select("#generate-text-vector-denoise-latent-tokens-container")
                .append("div")
                    .append("div")
                    .attr("class", "generate-text-vector-denoise-latent-token")
                    .text(tokens[i])
            d3.select("#generate-text-vector-denoise-latent-vectors-container")
                .append("div")
                    .attr("class", "generate-text-vector-denoise-latent-vector")
                    .attr("id", `generate-text-vector-denoise-latent-vector-${i}`)
            for (let j = 0 ; j< vectorDim ; j++) {
                d3.select(`#generate-text-vector-denoise-latent-vector-${i}`)
                    .append("div")
                        .attr("class", "generate-text-vector-denoise-latent-vector-cell")
                        .text(Math.round(+(vectors[i][j])*100)/100)
                        .style("left", `${21*j}px`)
            }
            d3.select(`#generate-text-vector-denoise-latent-vector-${i}`)
                .append("div")
                    .attr("class", "generate-text-vector-denoise-latent-vector-cell generate-text-vector-denoise-latent-vector-cell-last")
                    .style("left", `${21*vectorDim}px`)
                    
            d3.select(`#generate-text-vector-denoise-latent-vector-${i}`)
                .append("svg")
                    .attr("class", "generate-text-vector-denoise-latent-vector-horizontal-dots-svg")
                    .attr("id", `generate-text-vector-denoise-latent-vector-horizontal-dots-svg-${i}`)
            d3.select(`#generate-text-vector-denoise-latent-vector-horizontal-dots-svg-${i}`).append("circle").attr("r", "1.5").attr("cx","16").attr("cy", "11").attr("class", "dots")
            d3.select(`#generate-text-vector-denoise-latent-vector-horizontal-dots-svg-${i}`).append("circle").attr("r", "1.5").attr("cx","22").attr("cy", "11").attr("class", "dots")
            d3.select(`#generate-text-vector-denoise-latent-vector-horizontal-dots-svg-${i}`).append("circle").attr("r", "1.5").attr("cx","28").attr("cy", "11").attr("class", "dots")
        }

        d3.select("#generate-text-vector-l2-tokenizer-encoder-container")
            .append("div")
            .attr("id", "generate-text-vector-l2-tokenizer-encoder-tokens-container")

        for (let i = 0 ; i < window.tokens.length ; i ++) {
            let containerId = "generate-text-vector-l2-tokenizer-encoder-tokens-container"
            d3.select(`#${containerId}`)
                .append("div")
                    .attr("class", "generate-text-vector-denoise-latent-token")
                    .text(window.tokens[i])
            if (+getComputedStyle(document.getElementById(containerId))["height"].slice(0,-2) > 70) {
                document.getElementById(containerId).lastChild.remove();
                break;
            }
        }

        d3.select(`#generate-text-vector-l2-tokenizer-encoder-container`).append("svg").attr("id", "generate-text-vector-l2-tokenizer-encoder-token-dots-svg")
        d3.select("#generate-text-vector-l2-tokenizer-encoder-token-dots-svg").append("circle").attr("r", "1.5").attr("cx","68").attr("cy", "8").attr("class", "dots")
        d3.select("#generate-text-vector-l2-tokenizer-encoder-token-dots-svg").append("circle").attr("r", "1.5").attr("cx","68").attr("cy", "14").attr("class", "dots")
        d3.select("#generate-text-vector-l2-tokenizer-encoder-token-dots-svg").append("circle").attr("r", "1.5").attr("cx","68").attr("cy", "20").attr("class", "dots")

        // INPUT LATENTS
        d3.select("#denoise-latent-l2-expl-prev-latent-img")
            .attr("src", `./assets/latents/${selectedPromptGroupName}/${selectedData["prompts"][0]}_${timestep}_${seed}_${gs}.jpg`)
    })


