d3.select("#header")
    .append("div")
        .attr("id", "header-title")
        .append("img")
        .attr("id", "header-logo")
        .attr("src", "./icons/logo.svg")
d3.select("#header-title")
    .append("div")
        .text("Diffusion Explainer")

d3.select("#header")
    .append("div")
    .attr("id", "header-message")

d3.select("#header-message")
    .append("div")
        .attr("id", "header-message-1")
        .text("Learn how Stable Diffusion transforms")
d3.select("#header-message")
    .append("div")
        .attr("id", "header-message-2")
        .text("your text prompt")
d3.select("#header-message")
    .append("div")
        .attr("id", "header-message-3")
        .text("into")
d3.select("#header-message")
    .append("div")
        .attr("id", "header-message-4")
        .text("image")
d3.select("#header-message")
    .append("div")
        .attr("id", "header-message-5")
        .text("!")