d3.select("#header")
    .append("a")
        .attr("id", "header-title")
        .attr("href", "https://poloclub.github.io/diffusion-explainer/")
        .append("img")
        .attr("id", "header-logo")
        .attr("src", "./icons/logo.svg")
d3.select("#header-title")
    .append("div")
        .text("Diffusion Explainer")

d3.select("#header")
    .append("div")
    .attr("id", "header-message")

d3.select("#header-message")
    .append("div")
        .attr("id", "header-message-1")
        .text("Learn how Stable Diffusion transforms")
d3.select("#header-message")
    .append("div")
        .attr("id", "header-message-2")
        .text("your text prompt")
d3.select("#header-message")
    .append("div")
        .attr("id", "header-message-3")
        .text("into")
d3.select("#header-message")
    .append("div")
        .attr("id", "header-message-4")
        .text("image")
d3.select("#header-message")
    .append("div")
        .attr("id", "header-message-5")
        .text("!")

        
d3.select("#header")
    .append("div")
    .attr("id", "header-links")

d3.select("#header-links")
    .append("a")
        .attr("class", "header-link")
        .attr("id", "header-link-github")
        .attr("target", "_blank")
        .attr("href", "https://github.com/poloclub/diffusion-explainer")
        .append("img")
            .attr("id", "header-link-img-github")
            .attr("class", "header-link-img")
            .attr("src", "./icons/github.svg")
d3.select("#header-link-github")
    .append("div")
        .attr("id", "header-link-text-github")
        .attr("class", "header-link-text")
        .text("Code")

d3.select("#header-links")
    .append("a")
        .attr("class", "header-link")
        .attr("id", "header-link-paper")
        .attr("target", "_blank")
        .attr("href", "https://arxiv.org/abs/2305.03509")
        .append("img")
            .attr("id", "header-link-img-paper")
            .attr("class", "header-link-img")
            .attr("src", "./icons/document.svg")
d3.select("#header-link-paper")
    .append("div")
        .attr("id", "header-link-text-paper")
        .attr("class", "header-link-text")
        .text("Paper")

d3.select("#header-links")
    .append("a")
        .attr("class", "header-link")
        .attr("id", "header-link-youtube")
        .attr("target", "_blank")
        .attr("href", "https://youtu.be/Zg4gxdIWDds")
        .append("img")
            .attr("id", "header-link-img-youtube")
            .attr("class", "header-link-img")
            .attr("src", "./icons/youtube.svg")

d3.select("#header-link-youtube")
    .append("div")
        .attr("id", "header-link-text-youtube")
        .attr("class", "header-link-text")
        .text("Video")

d3.select("#header-links")
    .append("a")
        .attr("class", "header-link")
        .attr("id", "header-link-medium")
        .attr("target", "_blank")
        .attr("href", "https://medium.com/@seongminleee/77b53f4f1c4")
        .append("img")
            .attr("id", "header-link-img-medium")
            .attr("class", "header-link-img")
            .attr("src", "./icons/medium.svg")

d3.select("#header-link-medium")
    .append("div")
        .attr("id", "header-link-text-medium")
        .attr("class", "header-link-text")
        .text("Blog")

